[package]
name = "rustpy"
version = "0.1.0"
authors = ["Camden Reslink <camdenreslink@gmail.com>"]

[dependencies]
rustpy_compiler = { path = "../rustpy_compiler" }
rustpy_interpreter = { path = "../rustpy_interpreter" }
